import { ThemeConfig } from "@shared/schema";

export const themes: ThemeConfig[] = [
  {
    id: "nebula-purple",
    name: "Nebula Purple",
    description: "Deep space vibes",
    gradient: "radial-gradient(ellipse at top, hsl(262 83% 15%) 0%, hsl(240 6% 4%) 100%)",
    primary: "#00d9ff",
    secondary: "#8b5cf6",
    accent: "#ec4899",
  },
  {
    id: "solar-flare",
    name: "Solar Flare",
    description: "Warm energy",
    gradient: "radial-gradient(ellipse at top, hsl(15 83% 15%) 0%, hsl(240 6% 4%) 100%)",
    primary: "#f97316",
    secondary: "#eab308",
    accent: "#dc2626",
  },
  {
    id: "matrix-green",
    name: "Matrix Green",
    description: "Digital realm",
    gradient: "radial-gradient(ellipse at top, hsl(120 83% 15%) 0%, hsl(240 6% 4%) 100%)",
    primary: "#00ff41",
    secondary: "#10b981",
    accent: "#84cc16",
  },
  {
    id: "cyber-pink",
    name: "Cyber Pink",
    description: "Neon nights",
    gradient: "radial-gradient(ellipse at top, hsl(340 83% 15%) 0%, hsl(240 6% 4%) 100%)",
    primary: "#ff0080",
    secondary: "#ec4899",
    accent: "#f472b6",
  },
  {
    id: "arctic-blue",
    name: "Arctic Blue",
    description: "Frozen beauty",
    gradient: "radial-gradient(ellipse at top, hsl(200 83% 15%) 0%, hsl(240 6% 4%) 100%)",
    primary: "#0ea5e9",
    secondary: "#3b82f6",
    accent: "#06b6d4",
  },
  {
    id: "cosmic-violet",
    name: "Cosmic Violet",
    description: "Otherworldly elegance",
    gradient: "radial-gradient(ellipse at top, hsl(280 83% 15%) 0%, hsl(240 6% 4%) 100%)",
    primary: "#a855f7",
    secondary: "#7c3aed",
    accent: "#c084fc",
  },
  {
    id: "quantum-gold",
    name: "Quantum Gold",
    description: "Luxurious technology",
    gradient: "radial-gradient(ellipse at top, hsl(45 83% 15%) 0%, hsl(240 6% 4%) 100%)",
    primary: "#fbbf24",
    secondary: "#f59e0b",
    accent: "#fcd34d",
  },
  {
    id: "plasma-red",
    name: "Plasma Red",
    description: "Intense energy",
    gradient: "radial-gradient(ellipse at top, hsl(0 83% 15%) 0%, hsl(240 6% 4%) 100%)",
    primary: "#ef4444",
    secondary: "#dc2626",
    accent: "#f87171",
  },
  {
    id: "void-black",
    name: "Void Black",
    description: "Pure darkness",
    gradient: "radial-gradient(ellipse at top, hsl(240 10% 8%) 0%, hsl(240 10% 2%) 100%)",
    primary: "#6b7280",
    secondary: "#4b5563",
    accent: "#9ca3af",
  },
  {
    id: "aurora-spectrum",
    name: "Aurora Spectrum",
    description: "Northern lights magic",
    gradient: "radial-gradient(ellipse at top, hsl(180 83% 15%) 0%, hsl(240 6% 4%) 100%)",
    primary: "#06b6d4",
    secondary: "#10b981",
    accent: "#8b5cf6",
  },
];
